# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7afc4dfaca841a773414ee36f017e7f208f1126443d3815a5104d71c245e295dcec6ecc30a3692ec21ac8bacd387a442e205f3922718727a58f348daff5c8eb

test:
  secret_key_base: 37234418afd880ee5f14248ada9d166151d756e346f0d3c6617746c43fde733e758c59dbe2b109992c1d7510d00ed988c7b01996f8d0f1b76ef20b70afc8d482

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
